export const options_styles = {
  container: (provided) => ({
    ...provided,
    height: "100%",
  }),
  control: (provided) => ({
    ...provided,
    height: "100%",
    border: "1px solid rgba(220,220,220)",
    outline: "none",
    boxShadow: "none",
    cursor: "pointer",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
  valueContainer: (provided) => ({
    ...provided,
    height: "100%",
    padding: "0px 10px",
  }),
  input: (provided) => ({
    ...provided,
    margin: "0px",
    padding: "0px",
  }),
};

export const phoneinput_options = {
  type: "tel",
  country: "in",
  onlyCountries: ["in"],
  countryCodeEditable: false,
  placeholder: "phone Number",
};

// Select Options ----------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------

export const languages_options = [
  { value: "Telugu", label: "Telugu", name: "motherlanguage" },
  { value: "Hindi", label: "Hindi", name: "motherlanguage" },
  { value: "English", label: "English", name: "motherlanguage" },
  { value: "Tamil", label: "Tamil", name: "motherlanguage" },
  { value: "Kannada", label: "Kannada", name: "motherlanguage" },
  { value: "Malayalam", label: "Malayalam", name: "motherlanguage" },
  { value: "Punjabi", label: "Punjabi", name: "motherlanguage" },
  { value: "Oriya", label: "Oriya", name: "motherlanguage" },
  { value: "Urdu", label: "Urdu", name: "motherlanguage" },
  { value: "Marathi", label: "Marathi", name: "motherlanguage" },
  { value: "Bangla", label: "Bangla", name: "motherlanguage" },
  { value: "Gujarathi", label: "Gujarathi", name: "motherlanguage" },
];

export const autition_types = [
  { value: "1", label: "Online", name: "type" },
  { value: "2", label: "Physical", name: "type" },
];

export const gender_options = [
  { value: "male", label: "Male", name: "gender" },
  { value: "female", label: "Female", name: "gender" },
  { value: "other", label: "Other", name: "gender" },
];

export const category_options = [
  { value: "Artist", label: "Artist", name: "category" },
  { value: "Anchor", label: "Anchor", name: "category" },
  { value: "Choreographer", label: "Choreographer", name: "category" },
  { value: "Dancer", label: "Dancer", name: "category" },
  { value: "Director", label: "Director", name: "category" },
  { value: "DOP", label: "DOP", name: "category" },
  { value: "Musician", label: "Musician", name: "category" },
  { value: "Singer", label: "Singer", name: "category" },
  { value: "Stunt Master", label: "Stunt Master", name: "category" },
  { value: "Stuntman/woman", label: "Stuntman/woman", name: "category" },
  { value: "Writer", label: "Writer", name: "category" },
  { value: "NewsReader", label: "News Reader", name: "category" },
];

export const subcategory_options = [
  { value: "Hero", label: "Hero", name: "subcategory", target: "Artist" },
  { value: "Heroine", label: "Heroine", name: "subcategory", target: "Artist" },
  { value: "Villain", label: "Villain", name: "subcategory", target: "Artist" },
  {
    value: "Comedian",
    label: "Comedian",
    name: "subcategory",
    target: "Artist",
  },
  {
    value: "Supporting Role",
    label: "Supporting Role",
    name: "subcategory",
    target: "Artist",
  },
  {
    value: "Jr Artist",
    label: "Jr Artist",
    name: "subcategory",
    target: "Artist",
  },
  { value: "Others", label: "Others", name: "subcategory", target: "Artist" },

  {
    value: "Classical",
    label: "Classical",
    name: "subcategory",
    target: "Choreographer",
  },
  {
    value: "Folk",
    label: "Folk",
    name: "subcategory",
    target: "Choreographer",
  },
  {
    value: "Western",
    label: "Western",
    name: "subcategory",
    target: "Choreographer",
  },

  {
    value: "Classical",
    label: "Classical",
    name: "subcategory",
    target: "Dancer",
  },
  { value: "Folk", label: "Folk", name: "subcategory", target: "Dancer" },
  { value: "Western", label: "Western", name: "subcategory", target: "Dancer" },

  { value: "Films", label: "Films", name: "subcategory", target: "Director" },
  {
    value: "Non-Fiction",
    label: "Non-Fiction",
    name: "subcategory",
    target: "Director",
  },
  { value: "Songs", label: "Songs", name: "subcategory", target: "Director" },
  {
    value: "TV Serials",
    label: "TV Serials",
    name: "subcategory",
    target: "Director",
  },
  {
    value: "Web Series",
    label: "Web Series",
    name: "subcategory",
    target: "Director",
  },

  { value: "Films", label: "Films", name: "subcategory", target: "DOP" },
  {
    value: "Non-Fiction",
    label: "Non-Fiction",
    name: "subcategory",
    target: "DOP",
  },
  { value: "Songs", label: "Songs", name: "subcategory", target: "DOP" },
  {
    value: "TV Serials",
    label: "TV Serials",
    name: "subcategory",
    target: "DOP",
  },
  {
    value: "Web Series",
    label: "Web Series",
    name: "subcategory",
    target: "DOP",
  },

  { value: "Films", label: "Films", name: "subcategory", target: "Musician" },
  {
    value: "Non-Fiction",
    label: "Non-Fiction",
    name: "subcategory",
    target: "Musician",
  },
  { value: "Songs", label: "Songs", name: "subcategory", target: "Musician" },
  {
    value: "TV Serials",
    label: "TV Serials",
    name: "subcategory",
    target: "Musician",
  },
  {
    value: "Web Series",
    label: "Web Series",
    name: "subcategory",
    target: "Musician",
  },

  {
    value: "Classical",
    label: "Classical",
    name: "subcategory",
    target: "Singer",
  },
  {
    value: "Devotional",
    label: "Devotional",
    name: "subcategory",
    target: "Singer",
  },
  { value: "Folk", label: "Folk", name: "subcategory", target: "Singer" },
  { value: "Ghazals", label: "Ghazals", name: "subcategory", target: "Singer" },
  {
    value: "Indi Pop",
    label: "Indi Pop",
    name: "subcategory",
    target: "Singer",
  },
  {
    value: "Qawwalli",
    label: "Qawwalli",
    name: "subcategory",
    target: "Singer",
  },
  { value: "Western", label: "Western", name: "subcategory", target: "Singer" },

  {
    value: "Martial Arts Expert",
    label: "Martial Arts Expert",
    name: "subcategory",
    target: "Stunt Master",
  },
  {
    value: "Stunts Assistant",
    label: "Stunts Assistant",
    name: "subcategory",
    target: "Stunt Master",
  },
  {
    value: "Stunts Supporting Team",
    label: "Stunts Supporting Team",
    name: "subcategory",
    target: "Stunt Master",
  },
  {
    value: "Special Expert",
    label: "Special Expert",
    name: "subcategory",
    target: "Stunt Master",
  },
  {
    value: "Stunt Master",
    label: "Stunt Master",
    name: "subcategory",
    target: "Stunt Master",
  },

  {
    value: "Karate",
    label: "Karate",
    name: "subcategory",
    target: "Stuntman/woman",
  },
  {
    value: "Boxing",
    label: "Boxing",
    name: "subcategory",
    target: "Stuntman/woman",
  },
  {
    value: "Taekwondo",
    label: "Taekwondo",
    name: "subcategory",
    target: "Stuntman/woman",
  },
  {
    value: "Kungfu",
    label: "Kungfu",
    name: "subcategory",
    target: "Stuntman/woman",
  },
  {
    value: "Others",
    label: "Others",
    name: "subcategory",
    target: "Stuntman/woman",
  },

  {
    value: "Story development",
    label: "Story development",
    name: "subcategory",
    target: "Writer",
  },
  {
    value: "Screenplay",
    label: "Screenplay",
    name: "subcategory",
    target: "Writer",
  },
  {
    value: "Dialogues",
    label: "Dialogues",
    name: "subcategory",
    target: "Writer",
  },
  {
    value: "Song lyrics",
    label: "Song lyrics",
    name: "subcategory",
    target: "Writer",
  },
];

export const Height_options = [
  { value: "2 ft ' 1 in", label: "2 ft ' 1 in", name: "height" },
  { value: "2 ft ' 2 in", label: "2 ft ' 2 in", name: "height" },
  { value: "2 ft ' 3 in", label: "2 ft ' 3 in", name: "height" },
  { value: "2 ft ' 4 in", label: "2 ft ' 4 in", name: "height" },
  { value: "2 ft ' 5 in", label: "2 ft ' 5 in", name: "height" },
  { value: "2 ft ' 6 in", label: "2 ft ' 6 in", name: "height" },
  { value: "2 ft ' 7 in", label: "2 ft ' 7 in", name: "height" },
  { value: "2 ft ' 8 in", label: "2 ft ' 8 in", name: "height" },
  { value: "2 ft ' 9 in", label: "2 ft ' 9 in", name: "height" },
  { value: "2 ft ' 10 in", label: "2 ft ' 10 in", name: "height" },
  { value: "2 ft ' 11 in", label: "2 ft ' 11 in", name: "height" },
  { value: "2 ft ' 12 in", label: "2 ft ' 12 in", name: "height" },
  { value: "3 ft ' 1 in", label: "3 ft ' 1 in", name: "height" },
  { value: "3 ft", label: "3 ft", name: "height" },
  { value: "3 ft ' 2 in", label: "3 ft ' 2 in", name: "height" },
  { value: "3 ft ' 3 in", label: "3 ft ' 3 in", name: "height" },
  { value: "3 ft ' 4 in", label: "3 ft ' 4 in", name: "height" },
  { value: "3 ft ' 5 in", label: "3 ft ' 5 in", name: "height" },
  { value: "3 ft ' 6 in", label: "3 ft ' 6 in", name: "height" },
  { value: "3 ft ' 7 in", label: "3 ft ' 7 in", name: "height" },
  { value: "3 ft ' 8 in", label: "3 ft ' 8 in", name: "height" },
  { value: "3 ft ' 9 in", label: "3 ft ' 9 in", name: "height" },
  { value: "3 ft ' 10 in", label: "3 ft ' 10 in", name: "height" },
  { value: "3 ft ' 11 in", label: "3 ft ' 11 in", name: "height" },
  { value: "3 ft ' 12 in", label: "3 ft ' 12 in", name: "height" },
  { value: "4 ft", label: "4 ft", name: "height" },
  { value: "4 ft ' 1 in", label: "4 ft ' 1 in", name: "height" },
  { value: "4 ft ' 2 in", label: "4 ft ' 2 in", name: "height" },
  { value: "4 ft ' 3 in", label: "4 ft ' 3 in", name: "height" },
  { value: "4 ft ' 4 in", label: "4 ft ' 4 in", name: "height" },
  { value: "4 ft ' 5 in", label: "4 ft ' 5 in", name: "height" },
  { value: "4 ft ' 6 in", label: "4 ft ' 6 in", name: "height" },
  { value: "4 ft ' 7 in", label: "4 ft ' 7 in", name: "height" },
  { value: "4 ft ' 8 in", label: "4 ft ' 8 in", name: "height" },
  { value: "4 ft ' 9 in", label: "4 ft ' 9 in", name: "height" },
  { value: "4 ft ' 10 in", label: "4 ft ' 10 in", name: "height" },
  { value: "4 ft ' 11 in", label: "4 ft ' 11 in", name: "height" },
  { value: "4 ft ' 12 in", label: "4 ft ' 12 in", name: "height" },
  { value: "5 ft", label: "5 ft", name: "height" },
  { value: "5 ft ' 1 in", label: "5 ft ' 1 in", name: "height" },
  { value: "5 ft ' 2 in", label: "5 ft ' 2 in", name: "height" },
  { value: "5 ft ' 3 in", label: "5 ft ' 3 in", name: "height" },
  { value: "5 ft ' 4 in", label: "5 ft ' 4 in", name: "height" },
  { value: "5 ft ' 5 in", label: "5 ft ' 5 in", name: "height" },
  { value: "5 ft ' 6 in", label: "5 ft ' 6 in", name: "height" },
  { value: "5 ft ' 7 in", label: "5 ft ' 7 in", name: "height" },
  { value: "5 ft ' 8 in", label: "5 ft ' 8 in", name: "height" },
  { value: "5 ft ' 9 in", label: "5 ft ' 9 in", name: "height" },
  { value: "5 ft ' 10 in", label: "5 ft ' 10 in", name: "height" },
  { value: "5 ft ' 11 in", label: "5 ft ' 11 in", name: "height" },
  { value: "5 ft ' 12 in", label: "5 ft ' 12 in", name: "height" },
  { value: "6 ft", label: "6 ft", name: "height" },
  { value: "6 ft ' 1 in", label: "6 ft ' 1 in", name: "height" },
  { value: "6 ft ' 2 in", label: "6 ft ' 2 in", name: "height" },
  { value: "6 ft ' 3 in", label: "6 ft ' 3 in", name: "height" },
  { value: "6 ft ' 4 in", label: "6 ft ' 4 in", name: "height" },
  { value: "6 ft ' 5 in", label: "6 ft ' 5 in", name: "height" },
  { value: "6 ft ' 6 in", label: "6 ft ' 6 in", name: "height" },
  { value: "6 ft ' 7 in", label: "6 ft ' 7 in", name: "height" },
  { value: "6 ft ' 8 in", label: "6 ft ' 8 in", name: "height" },
  { value: "6 ft ' 9 in", label: "6 ft ' 9 in", name: "height" },
  { value: "6 ft ' 10 in", label: "6 ft ' 10 in", name: "height" },
  { value: "6 ft ' 11 in", label: "6 ft ' 11 in", name: "height" },
  { value: "6 ft ' 12 in", label: "6 ft ' 12 in", name: "height" },
  { value: "7 ft", label: "7 ft", name: "height" },
  { value: "7 ft ' 1 in", label: "7 ft ' 1 in", name: "height" },
  { value: "7 ft ' 2 in", label: "7 ft ' 2 in", name: "height" },
  { value: "7 ft ' 3 in", label: "7 ft ' 3 in", name: "height" },
  { value: "7 ft ' 4 in", label: "7 ft ' 4 in", name: "height" },
  { value: "7 ft ' 5 in", label: "7 ft ' 5 in", name: "height" },
  { value: "7 ft ' 6 in", label: "7 ft ' 6 in", name: "height" },
  { value: "7 ft ' 7 in", label: "7 ft ' 7 in", name: "height" },
  { value: "7 ft ' 8 in", label: "7 ft ' 8 in", name: "height" },
  { value: "7 ft ' 9 in", label: "7 ft ' 9 in", name: "height" },
  { value: "7 ft ' 10 in", label: "7 ft ' 10 in", name: "height" },
  { value: "7 ft ' 11 in", label: "7 ft ' 11 in", name: "height" },
  { value: "7 ft ' 12 in", label: "7 ft ' 12 in", name: "height" },
];
